name: Build .vl2 file

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Build and release a vl2 using the vl2-builder action
        id: "release"
        uses: tribes2/vl2-builder@v1.3
        with:
          tag-name: ${{ github.ref_name }}
          archive-prefix: "Rev_TeamRabbit2_2025"
          exclude-patterns: ".git/*, *.zip, *.vl2, .github/*"
      - name: Report build success for the fun of it
        run: |
          echo "Successfully released asset: ${{ steps.release.outputs.asset_name }}"
